-- ==============================================================================
-- ROUTEX INITIALIZATION MIGRATION
-- 
-- Creates the foundational route and ticket tables that are missing from 
-- the live Supabase database but expected by the Flutter application.
-- 
-- Includes:
-- 1. public.stops
-- 2. public.bus_routes
-- 3. public.tickets
-- 
-- All tables are created idempotently (CREATE TABLE IF NOT EXISTS).
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. STOPS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.stops (
  id TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  name_ta TEXT NOT NULL,
  district TEXT NOT NULL
);

ALTER TABLE public.stops ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Stops are publicly readable" ON public.stops FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------------------
-- 2. BUS ROUTES TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bus_routes (
  id TEXT PRIMARY KEY,
  bus_number TEXT NOT NULL,
  bus_name TEXT NOT NULL,
  from_id TEXT NOT NULL REFERENCES public.stops(id),
  to_id TEXT NOT NULL REFERENCES public.stops(id),
  departure TEXT NOT NULL,
  arrival TEXT NOT NULL,
  duration_minutes INTEGER NOT NULL,
  price INTEGER NOT NULL,
  route_type TEXT NOT NULL CHECK (route_type IN ('direct', 'stops')),
  status TEXT NOT NULL DEFAULT 'onTime' CHECK (status IN ('onTime', 'delayed')),
  bus_type TEXT NOT NULL CHECK (bus_type IN ('ordinary', 'express', 'superDeluxe', 'ac')),
  intermediate_stops TEXT[] DEFAULT '{}'
);

ALTER TABLE public.bus_routes ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Bus routes are publicly readable" ON public.bus_routes FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------------------------------
-- 3. TICKETS TABLE
-- ------------------------------------------------------------------------------
-- Note: The schema for this table has been ADAPTED to perfectly match the 
-- actual fields generated by the Flutter application in BusDetailsPage.dart 
-- and expected by MyTicketsPage.dart, discarding the unused/incompatible 
-- columns from the original 20260510 migration.
CREATE TABLE IF NOT EXISTS public.tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  ticket_number TEXT NOT NULL UNIQUE,
  passenger_name TEXT NOT NULL,
  route TEXT,
  bus_number TEXT,
  fare TEXT,
  travel_date TEXT,
  status TEXT NOT NULL DEFAULT 'Valid',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Users can view their own tickets" ON public.tickets FOR SELECT USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "Users can create their own tickets" ON public.tickets FOR INSERT WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Index for querying tickets efficiently by user_id and created_at
CREATE INDEX IF NOT EXISTS idx_tickets_user ON public.tickets(user_id, created_at DESC);
